#!/usr/bin/perl
use strict;
use warnings;
use Math::CDF;
use PDL;
use PDL::LiteF;
use PDL::Stats::Distr;
use Data::Dumper;
use Statistics::Basic::Mean;
use Set::IntSpan::Fast;
use Getopt::Long;
use Math::Round::Var;


no autovivification;



my $usage = "

Synopsis:

NO_CALL -c bgi.depth.file -g your.gvf -d 5 -q 15 

Description:

I will create no-call data for you on unfiltered gvfs including the low quality SNPs/INDELs. 
Here are important things:

1) Make sure you have coverage information for the entire gvf file you want to no call. 
This script wont throw an error, but unknown depth regions wont be edited. 

2) This scirpt takes the strange BGI depth format:  

>chr1
1 2 3 4 6 0 1 
>chr2
0 0 0 0 0 200

I have a parser \"to_bgi_depth\" in my github tool repository that takes samtools generated depth files
and converts the format.  

";

my ($help);
my $bgi_depth;
my $gvf;
my $quality;
my $depth;
my $coverage;

my $opt_success = GetOptions('help'       => \$help,
                             "depth=s"    => \$depth,
			     "coverage=s" => \$coverage,
			     "gvf=s"      => \$gvf, 
			     "quality=s"  => \$quality,
                             );

die $usage if $help || ! $opt_success;
die $usage unless defined $gvf && defined $depth && defined $quality; 


my %NO_CALL_POS;
my %GVF;
my %CUTOFF_LOOKUP;



#-----------------------------------------------------------------------------
#----------------------------------- MAIN ------------------------------------
#-----------------------------------------------------------------------------
Parse_Gvf($gvf);
print STDERR "done loading gvf\n";
Process_Cut_Off($coverage);
Print_Gvf();

#-----------------------------------------------------------------------------
#-------------------------------- SUBROUTINES --------------------------------
#-----------------------------------------------------------------------------
sub Process_Cut_Off {
    my $file = shift;
    open(FH, '<', $file) || die "cannot open $file for reading!\n";
    $/ = ">";
    my $count = 0;
    while (my $line = <FH>) {
	$count++;
	next if $count ==1;
	my @a = split /\s+/,$line if $line  ne '>';
       	my ($contig) = shift @a;
	print STDERR "working on the feature $contig\n";
	pop @a;
	my $lambda = Cut_Off(\@a);
	my $cutoff = $CUTOFF_LOOKUP{$lambda};
	No_Call_Pos(\@a, $contig, $cutoff);
    }
    close FH;
    $/ = '\n';
}
#-----------------------------------------------------------------------------
sub Cut_Off{
        
    my $a      = shift;
    my $sum    = 0;
    my $count  = 0;
    
    next if !defined $a;

    foreach my $b(@{$a}){
	next if $b < 10;
	$count++;
	$sum += $b;
    }
    
    my $rnd = Math::Round::Var->new(0.1);
    
    my $lambda = $sum / $count if $sum > 0;
    $lambda = 0 if $sum == 0;
    $lambda = $rnd->round($lambda);
    return $lambda if exists $CUTOFF_LOOKUP{$lambda};
    my $pcutoff;
    $pcutoff = Math::CDF::qpois(0.98, $lambda) if $lambda > 0;
    $pcutoff = 0 if $lambda == 0;
    $pcutoff = $rnd->round($pcutoff);
    $CUTOFF_LOOKUP{$lambda} = $pcutoff;
    return $lambda;
}             

#-----------------------------------------------------------------------------
sub No_Call_Pos{
    my $var    = shift;
    my $contig = shift;
    my $pcut   = shift;
    my $count  = 0;
    my @nocall = ();
    my $set = Set::IntSpan::Fast->new();
    foreach my $d (@{$var}){
	$count++;
	push @nocall, $count if $d > $pcut || $d < $depth;
	#print "$pcut\t$d\t$count\n" if $d > 100;
    }
    $set->add(@nocall); 
    my $ranges = $set->as_string();
    Del_Range($contig, $ranges);
}

#-----------------------------------------------------------------------------

sub Parse_Gvf{
    my $file = shift;
    open(FH, '<', $file);
    while(<FH>){
	chomp;
	next if /^\s+/;
	next if /#/;
	my ($seqid, $source, $type, $start, $end, $score, $strand, $phase, 
	    $attributes) = split /\t/, $_;
	$GVF{$seqid}{$start}{$end} = "$type\t$source\t$score\t$strand\t$phase\t$attributes";
	
    }
    close FH;
}

#-----------------------------------------------------------------------------

sub Del_Range{

    my $contig  = shift;
    my $ranges  = shift;
    my @ranges = split /,/, $ranges;
    
    for my $range (@ranges){
	my @ab_range;
	if($range =~ /-/){
	    @ab_range = split /-/, $range;
	}else{
	    @ab_range = ($range, $range);
	}
	for(my $i = $ab_range[0]; $i <= $ab_range[1]; $i++){
	    delete $GVF{$contig}{$i};
	}
	GVF_Line($contig, \@ab_range);
    }
}

#-----------------------------------------------------------------------------

sub GVF_Line{
    my $contig = shift;
    my $range  = shift;
    my @range = @{$range};
    $GVF{$contig}{$range[0]}{$range[1]} = "gap\tno_call\t.\t.\t.\tID=$contig:$range[0]:$range[1];";    
}
    
#-----------------------------------------------------------------------------

sub Print_Gvf{
   while(my($seqid, $start_hash) =  each %GVF){
       foreach my $start (sort {$a <=> $b} keys %{$GVF{$seqid}}){
	   foreach my $end (sort {$a <=> $b} keys %{$GVF{$seqid}{$start}}){
	       my $value = $GVF{$seqid}{$start}{$end};
	       my ($type, $source, $score, $strand, $phase, $attributes) = split /\t/, $value;
	       if ($score !~ /\./ && $score < $quality){
		   $source = "no_call";
		   $attributes =~ s/Variant_seq=.*?;/Variant_seq=^;/;
		   $attributes =~ s/Genotype=.*?;/Genotype=0:0;/;
	       }
	       
	       print "$seqid\t$source\t$type\t$start\t$end\t$score\t$strand\t$phase\t$attributes\n";
	   }
       }
   }
}

#-----------------------------------------------------------------------------

